# Workflow name
name: CD

# Events policy
on:
  push:
    branches:
    - main

# Workflow jobs
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Build Container
      uses: mr-smithers-excellent/docker-build-push@v2
      with:
        image: huy1219/hello-world
        tag: ${{ github.sha }}
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
  deploy:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout Infra Repo
        uses: actions/checkout@v2
        with:
          repository: huytn1219/infra

